//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebArtAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class FabricRollmaster
    {
        public decimal Roll_PK { get; set; }
        public string RollNum { get; set; }
        public decimal SkuDet_PK { get; set; }
        public Nullable<decimal> Po_PK { get; set; }
        public Nullable<decimal> MRnDet_PK { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string UOM { get; set; }
        public string Remark { get; set; }
        public string SShrink { get; set; }
        public string SYard { get; set; }
        public string SShade { get; set; }
        public string SWidth { get; set; }
        public string AShrink { get; set; }
        public string AShade { get; set; }
        public string AWidth { get; set; }
        public Nullable<decimal> AYard { get; set; }
        public string IsSaved { get; set; }
        public string IsApproved { get; set; }
        public string IsAcceptable { get; set; }
        public string MarkerType { get; set; }
        public string SGsm { get; set; }
        public string AGsm { get; set; }
        public Nullable<decimal> podet_pk { get; set; }
        public string WidthGroup { get; set; }
        public string ShadeGroup { get; set; }
        public string ShrinkageGroup { get; set; }
        public string TotalDefect { get; set; }
        public string TotalDefecton100 { get; set; }
        public string TotalPoint { get; set; }
        public string TotalPointon100yard { get; set; }
        public Nullable<decimal> SupplierDoc_pk { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string InspectionApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string LOTnum { get; set; }
        public string SWeight { get; set; }
        public string IsDelivered { get; set; }
        public string IsCut { get; set; }
        public string IsMRN { get; set; }
        public Nullable<decimal> BaltoCut { get; set; }
        public string IsGrouped { get; set; }
        public Nullable<System.DateTime> GroupedDate { get; set; }
        public Nullable<System.DateTime> ValidatedDate { get; set; }
        public Nullable<System.DateTime> InspectedDate { get; set; }
    }
}
