//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebArtAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public decimal User_PK { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<decimal> UserLoc_PK { get; set; }
        public string PassCode { get; set; }
        public string IsAdmin { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<decimal> UserProfile_Pk { get; set; }
        public Nullable<decimal> Department_PK { get; set; }
    
        public virtual UserProfileMaster UserProfileMaster { get; set; }
    }
}
